char index[] = "<!DOCTYPE HTML>\r\n"
"<head>\r\n"
"	<script src=\"https://code.jquery.com/jquery-3.3.1.min.js\" integrity=\"sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=\" crossorigin=\"anonymous\"></script>\r\n"
"</head>\r\n"
"<html>\r\n"
"  <body style=\"font-family: 'Helvetica';\">\r\n"
"    <h1 style=\"font-size: 4em;\">Lights</h1>\r\n"
"    <span style=\"font-size: 3em\" id=\"powerStatus\"> </span>\r\n"
"    <span style=\"font-size: 3em\">&nbsp</span>\r\n"
"    <button style=\"font-size: 4em; border: none; background-color: #ddd\" onclick=\"javascript: update('/powerToggle');\" class=\"btn btn-primary mb-2\" id=\"powerButton\">&#8204</button>\r\n"
"    </br>\r\n"
"    </br>\r\n"
"    <button style=\"font-size: 3em; border: none; background-color: #ddd\" onclick=\"javascript: update('/white');\" class=\"btn btn-primary mb-2\">White</button>\r\n"
"    <button style=\"font-size: 3em; border: none; background-color: #ddd\" onclick=\"javascript: update('/solidColors');\" class=\"btn btn-primary mb-2\">Solid</button>\r\n"
"    <button style=\"font-size: 3em; border: none; background-color: #ddd\" onclick=\"javascript: update('/random');\" class=\"btn btn-primary mb-2\">Random</button>\r\n"
"    </br>\r\n"
"    <button style=\"font-size: 3em; border: none; background-color: #ddd\" onclick=\"javascript: update('/spectrum');\" class=\"btn btn-primary mb-2\">Spectrum</button>\r\n"
"    <button style=\"font-size: 3em; border: none; background-color: #ddd\" onclick=\"javascript: update('/gradient');\" class=\"btn btn-primary mb-2\">Gradient</button>\r\n"
"    </br>\r\n"
"    <button style=\"font-size: 3em; border: none; background-color: #ddd\" onclick=\"javascript: update('/flow');\" class=\"btn btn-primary mb-2\">Flow</button>\r\n"
"    <button style=\"font-size: 3em; border: none; background-color: #ddd\" onclick=\"javascript: update('/red');\" class=\"btn btn-primary mb-2\">Red</button>\r\n"
"    </br>\r\n"
"    </br>\r\n"
"    <button style=\"font-size: 3em; border: none; background-color: #ddd;\" onclick=\"javascript: update('/left');\" class=\"btn btn-primary mb-2\">&#8592</button>\r\n"
"    <button style=\"font-size: 3em; border: none; background-color: #ddd;\" onclick=\"javascript: update('/right');\" class=\"btn btn-primary mb-2\">&#8594</button>\r\n"
"		\r\n"
"	\r\n"
"    <script>\r\n"
"      function update(value) {\r\n"
"          $.ajax({\r\n"
"              method: 'get',\r\n"
"              url: value,\r\n"
"              success: function(data) {\r\n"
"                  \r\n"
"                  if (data.error) {\r\n"
"                    \r\n"
"                  }\r\n"
"                  else {\r\n"
"					\r\n"
"	                var redColor = data[\"r\"];\r\n"
"                    var greenColor = data[\"g\"];\r\n"
"                    var blueColor = data[\"b\"];\r\n"
"                    \r\n"
"                    $(\"body\").css(\"background-color\", \"rgb(\" + String(parseInt(String(redColor))) + \",\" + String(parseInt(String(greenColor))) + \",\" + String(parseInt(String(blueColor))) + \")\");\r\n"
"                    $(\"#powerButton\").text(String(data[\"powerButtonText\"]));\r\n"
"                    $(\"#powerStatus\").text(String(data[\"powerStatus\"]));\r\n"
"                  }\r\n"
"              }\r\n"
"          });\r\n"
"      }\r\n"
"    </script>\r\n"
"	<script>\r\n"
"		update('/json');\r\n"
"		setInterval(function() {\r\n"
"			update('/json');\r\n"
"		}, 200);\r\n"
"	</script>\r\n"
"	\r\n"
"  </body>\r\n"
"</html>";
